# -*- coding: utf-8 -*-
"""기후변화데이터 분석.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TIJYFr0dvksAcd82rCsjNIJU62R5wazU
"""

import pandas as pd
import matplotlib.pyplot as plt

file_path = './Annual_Surface_Temperature_Change.csv'
surface_temp_data = pd.read_csv(file_path)

# 나라 보기
available_countries = surface_temp_data['Country'].unique()
available_countries[:30]

south_korea_data = surface_temp_data[surface_temp_data['Country'] == 'Korea, Rep. of']
years = south_korea_data.columns[10:]
temperatures = south_korea_data.iloc[0][years]

plt.figure(figsize=(15, 6))
plt.plot(years, temperatures, marker='o', linestyle='-')
plt.title('Yearly Surface Temperature Change in South Korea (1960-2022)')
plt.xlabel('Year')
plt.ylabel('Temperature Change (°C)')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

# Selecting a few countries for comparison
selected_countries = ['United States of America', 'China', 'India', 'Brazil', 'Korea, Rep. of', 'Germany']
comparison_data = surface_temp_data[surface_temp_data['Country'].isin(selected_countries)]

# Extracting the latest year temperature change for comparison
latest_year = 'F2022'
latest_temperatures = comparison_data[['Country', latest_year]]

# Plotting the comparison as a bar chart
plt.figure(figsize=(12, 6))
plt.bar(latest_temperatures['Country'], latest_temperatures[latest_year], color='skyblue')
plt.title(f'Temperature Change in {latest_year} - Comparison among Selected Countries')
plt.xlabel('Country')
plt.ylabel(f'Temperature Change in {latest_year} (°C)')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.show()

import numpy as np

# Calculating the global average temperature change per year
global_avg_temperatures = surface_temp_data[years].mean()

# Plotting the global average temperature change over the years
plt.figure(figsize=(15, 6))
plt.plot(years, global_avg_temperatures, marker='o', linestyle='-', color='green')
plt.title('Global Average Yearly Surface Temperature Change (1960-2022)')
plt.xlabel('Year')
plt.ylabel('Average Temperature Change (°C)')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

